GIX-1545 ic-js: Import new candid (#336)
# Motivation

We want to use the `confirmation_text` and `restricted_countries` fields
in SNS participation on NNS dapp.

**Note**: This is a breaking change. The new fields are declared as
optional in Candid, but in TypeScript that results in types like `[] |
[string]` which are not optional. So when upgrading the ic-js dependency
those fields will be required to be at least `[]`.

# Changes

Each of these are a separate commit, which might help reviewing:

1. In `scripts/import-candid` change `icrc1.did` to `ledger.did`. The
former no longer exists and has been replaced by the latter.
2. In `scripts/compile-idl-js`, require version `didc 0.1.4`. I first
used `didc 0.1.6` and it caused breaking changes.
3. Run `scripts/import-candid`
4. Revert the changes in other packages than `sns`.
5. Run `scripts/compile-idl-js`
6. Fixed tests broken by the new non-optional fields.

# Tests

Tested the changes in nns-dapp as described in
https://github.com/dfinity/ic-js/blob/main/HACKING.md.
The changes broke nns-dapp but I was able to fix nns-dapp by dealing
with the new non-optional types.
You can see the required changes in
https://github.com/dfinity/nns-dapp/pull/2529/files

diff --git a/scripts/compile-idl-js b/scripts/compile-idl-js
--- a/scripts/compile-idl-js
+++ b/scripts/compile-idl-js
@@ -4,6 +4,15 @@
 
 set -euo pipefail
 
+if [ "$(didc --version)" != "didc 0.1.4" ]; then
+  {
+    echo "didc version 0.1.4 is required. To install it on Mac:"
+    echo "curl -Lf https://github.com/dfinity/candid/releases/download/2022-08-09/didc-macos -o install_didc"
+    echo "install -m 755 install_didc /$HOME/.local/bin/didc"
+  } >&2
+  exit 1
+fi
+
 did_files_to_compile_for_pkg() {
   local pkg="$1"
   local path=packages/${pkg}/candid
